admin_custom_stock_approval_dashboard:
  path: /customstocktransfer/approval
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\CustomStockTransfer\Controller\Admin\CustomStockApprovalController::indexAction'
    _legacy_controller: 'AdminCustomStockApproval'
    _legacy_link: 'AdminCustomStockApproval'

admin_custom_stock_transfer_dashboard:
  path: /customstocktransfer/transfer
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\CustomStockTransfer\Controller\Admin\CustomStockTransferController::indexAction'
    _legacy_controller: 'AdminCustomStockTransfer'
    _legacy_link: 'AdminCustomStockTransfer'