services:
  # Repositories
  PrestaShop\Module\Customstocktransfer\Repository\CustomStockApprovalRepository:
    class: PrestaShop\Module\Customstocktransfer\Repository\CustomStockApprovalRepository

  PrestaShop\Module\Customstocktransfer\Repository\CustomStockTransferRepository:
    class: PrestaShop\Module\Customstocktransfer\Repository\CustomStockTransferRepository

  # Services
  PrestaShop\Module\Customstocktransfer\Service\CustomStockApprovalService:
    class: PrestaShop\Module\Customstocktransfer\Service\CustomStockApprovalService
    arguments:
      - '@PrestaShop\Module\Customstocktransfer\Repository\CustomStockApprovalRepository'

  PrestaShop\Module\Customstocktransfer\Service\CustomStockTransferService:
    class: PrestaShop\Module\Customstocktransfer\Service\CustomStockTransferService
    arguments:
      - '@PrestaShop\Module\Customstocktransfer\Repository\CustomStockTransferRepository'

  # Controllers
  PrestaShop\Module\Customstocktransfer\Controller\Admin\CustomStockApprovalController:
    class: PrestaShop\Module\Customstocktransfer\Controller\Admin\CustomStockApprovalController
    arguments:
      - '@PrestaShop\Module\Customstocktransfer\Service\CustomStockApprovalService'
    tags:
      - { name: 'controller.service_arguments' }

  PrestaShop\Module\Customstocktransfer\Controller\Admin\CustomStockTransferController:
    class: PrestaShop\Module\Customstocktransfer\Controller\Admin\CustomStockTransferController
    arguments:
      - '@PrestaShop\Module\Customstocktransfer\Service\CustomStockTransferService'
    tags:
      - { name: 'controller.service_arguments' }